[[ -f $HOME/.xinitrc.local ]] && . $HOME/.xinitrc.local

setxkbmap -option ctrl:nocaps

if [ -d /etc/X11/xinit/xinitrc.d ]
then
    for f in /etc/X11/xinit/xinitrc.d/*
    do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

if [ "${PATH%%:*}" != "$HOME/bin" ]
then
    if [ -d "$HOME/bin" ]
    then
        PATH="$HOME/bin:$PATH"
    fi
fi

numlockx &

exec i3
