#!/usr/bin/env bash

BATTERY="$(acpi -b | grep -E -o '[0-9]{1,3}%')"

COLOR="#7f9f7f"
CODE=0
if [[ ${BATTERY%%%} -lt 10 ]]
then
    COLOR="#dca3a3"
    CODE=33
elif [[ ${BATTERY%%%} -gt 30 ]]
then
    COLOR="#c3bf9f"
fi

echo $BATTERY
echo
echo $COLOR

exit $CODE
