#!/usr/bin/env bash

if ! which acpi >/dev/null 2>&1
then
    exit 0
fi

battery_data="$(acpi -b | grep -E -o '[0-9]{1,3}%')"

is_charging="$(acpi -b | grep -i -o ' charging,')"

BATTERY=
for bat in $battery_data
do
    if [[ -z "$BATTERY" ]]
    then
        BATTERY="$bat"
    fi

    if [[ "${bat%%%}" -gt 0 ]]
    then
        BATTERY="$bat"
    fi
done

if [ -n "$is_charging" ]
then
    BATTERY="<span color='#7f9f7f'></span> $BATTERY"
fi

COLOR="#7f9f7f"
CODE=0
if [[ ${BATTERY%%%} -lt 5 ]]
then
    # i3-nagbar -m "Battery at ${BATTERY}" -f "pango:Input Mono 12" >/dev/null 2>&1 &
    COLOR="#dca3a3"
    CODE=33
elif [[ ${BATTERY%%%} -lt 10 ]]
then
    COLOR="#dca3a3"
    CODE=33
elif [[ ${BATTERY%%%} -lt 30 ]]
then
    COLOR="#c3bf9f"
fi

echo $BATTERY
echo
echo $COLOR

exit $CODE
