#!/usr/bin/env bash

CPU=($(sed -n 's/^cpu\s//p' /proc/stat))
IDLE=${CPU[3]}
TOTAL=0
for VAL in "${CPU[@]}"
do
    TOTAL=$(bc <<<"$TOTAL + $VAL")
done

sleep 1

CPU2=($(sed -n 's/^cpu\s//p' /proc/stat))
IDLE2=${CPU2[3]}
TOTAL2=0
for VAL in "${CPU2[@]}"
do
    TOTAL2=$(bc <<<"$TOTAL2 + $VAL")
done

DIFF_IDLE=$(bc <<<"$IDLE2 - $IDLE")
DIFF_TOTAL=$(bc <<<"$TOTAL2 - $TOTAL")

CPUPERC=$(bc <<<"(1000*($DIFF_TOTAL-$DIFF_IDLE)/$DIFF_TOTAL+5)/10")


COLOR="#7f9f7f"
if [[ $(bc <<<"$CPUPERC > 80") -eq 1 ]]
then
    COLOR="#dca3a3"
elif [[ $(bc <<<"$CPUPERC > 60") -eq 1 ]]
then
    COLOR="#c3bf9f"
fi

echo ${CPUPERC}%
echo
echo $COLOR
