#!/usr/bin/env bash

CPUPERC=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1}')

COLOR="#7f9f7f"
if [[ $(bc <<<"$CPUPERC > 80") -eq 1 ]]
then
    COLOR="#dca3a3"
elif [[ $(bc <<<"$CPUPERC > 60") -eq 1 ]]
then
    COLOR="#c3bf9f"
fi

echo ${CPUPERC}%
echo
echo $COLOR
