#!/usr/bin/env bash

partitions=$(lsblk | awk '{print $1":"$7}' | sed -e 1d -e 's/^[^a-zA-Z0-9]\+//' -e '/:$/d' -e '/SWAP/d')

output=""

for dp in $partitions
do
    disk="${dp%:*}"
    part="${dp##*:}"
    dfline="$(df -h "$part" | tail -1)"
    size="$(echo "$dfline" | awk '{print $2}')"
    used="$(echo "$dfline" | awk '{print $3}')"
    percent="$(echo "$dfline" | awk '{print $5}')"

    #a9a999
    color="#7f9f7f"
    if [[ ${percent%%%} -gt 85 ]]
    then
        color="#dca3a3"
    elif [[ ${percent%%%} -gt 75 ]]
    then
        color="#c3bf9f"
    fi
    output="$output <span color='#a9a999'>$disk @</span> $part <span color='$color'>$used/$size</span> "
done



echo "$output"
