#!/usr/bin/env bash

vpn_name="$(systemctl list-units --plain --state=active | grep openvpn-client@ | awk '{print $1}' | sed -e 's/openvpn-client@//' -e 's/.service//')"

externalIp="$(dig +short myip.opendns.com @resolver1.opendns.com)"

if [[ -z "$externalIp" ]] || [[ $(expr match "$externalIp" "[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}") -eq 0 ]]
then
    echo "0.0.0.0"
    exit 33
fi

color="#dca3a3"
lock=""

if [[ -n "$vpn_name" ]]
then
    color="#7f9f7f"
    lock=""
fi


echo $lock $externalIp $vpn_name
echo
echo $color
