#!/usr/bin/env bash

externalIp="$(dig +short myip.opendns.com @resolver1.opendns.com)"

if [[ -z "$externalIp" ]] || [[ $(expr match "$externalIp" "[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}") -eq 0 ]]
then
    echo "0.0.0.0"
    exit 33
fi

echo $externalIp
echo
echo 
