#!/usr/bin/env bash

pattern="NAME\s\?=\s\?"
kernelVersion=$(uname -r | sed "s/-.*//g")

# strip trailing .0 version, since the git tags on kernel.org do not have them
kernelVersion=${kernelVersion/%".0"/}
cacheFile="/tmp/kernelcodename-$USER"

if [ -f "$cacheFile" ]
then
    cache=$(cat $cacheFile)
    cachedVersion=$(expr "$cache" : '\([0-9.]*\)')
    cachedName=$(expr "$cache" : '.*@\([-A-Za-z ]*\)')

    if [ "$cachedVersion" = "$kernelVersion" ]
    then
        kernelCodename="$cachedName"
    fi
fi

if [ ! "$kernelCodename" ]
then
    url="https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/Makefile?id=refs/tags/v${kernelVersion}"
    kernelCodename=$(grep $pattern <<<"$(curl -s -L "$url")" | sed "s/$pattern//g")
fi

echo "$kernelVersion@$kernelCodename" > "$cacheFile"

echo "$kernelCodename ($kernelVersion)"
echo
echo "#83b3a3"
