#!/usr/bin/env bash

LOCALIP="$(ip addr | grep -E '(enp|wlp|wlan)[a-z0-9]+$' | sed -r 's/.* ([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})\/[0-9]{2}.*/\1/')"

if [[ -z "$LOCALIP" ]]
then
    echo "0.0.0.0"
    exit 33
fi

echo $LOCALIP
