#!/usr/bin/env bash

FAIL() {
    echo "0.0 b/s $SYMBOL"
    echo
    echo "#a9a999"
    exit 33
}

IF="$(ip addr | grep -o -E '(enp|wlp)[a-z0-9]+$')"

if [[ $1 = up ]]
then
    RT=tx
    SYMBOL=
else
    RT=rx
    SYMBOL=
fi

REPORT=B
if [[ -n "$2" ]] && [[ "$2" = "bits" ]]
then
    REPORT=b
fi

R1=$(cat /sys/class/net/$IF/statistics/${RT}_bytes) || FAIL
sleep 0.5s
R2=$(cat /sys/class/net/$IF/statistics/${RT}_bytes) || FAIL
BPS=$(bc <<<"($R2 - $R1)*2")
if [[ "$REPORT" = "b" ]]
then
    BPS=$(bc <<<"($R2 - $R1)*8")
fi

SCALE=0

while [[ $(bc <<<"$BPS >= 1024") -eq 1 ]]
do
    BPS=$(bc <<<"scale=2; $BPS / 1024")
    SCALE=$((SCALE+1))
done

case $SCALE in
    1) UNIT="K";;
    2) UNIT="M";;
    3) UNIT="G";;
esac

echo $BPS ${UNIT}${REPORT}/s $SYMBOL | sed 's/^\./0./'
echo
echo "#a9a999"
