#!/bin/bash
# Arch upgradeable packages

updates="$(checkupdates)"
count=$(echo -n "$updates" | wc -l)
linux_needs_upgrade=$(echo "$updates" | grep '^linux ')

COLOR="#7f9f7f"
if [[ $count -gt 50 ]]
then
    COLOR="#dca3a3"
elif [[ $count -gt 10 ]]
then
    COLOR="#c3bf9f"
fi

output=" <span color=\"$COLOR\">$count"

if [[ -n "$linux_needs_upgrade" ]]
then
    output="$output "
elif [[ "$count" -ne 0 ]]
then
    output="$output "
fi

echo "$output</span>"
echo
echo
