#!/bin/bash
# Arch upgradeable packages

count=$(cat <(checkupdates) <(pacaur -k) | wc -l)
linux_needs_upgrade=$(checkupdates | grep '^linux ')

COLOR="#7f9f7f"
if [[ $count -gt 50 ]]
then
    COLOR="#dca3a3"
elif [[ $count -gt 10 ]]
then
    COLOR="#c3bf9f"
fi

output="$count pending"

if [[ -n "$linux_needs_upgrade" ]]
then
    output="$output "
elif [[ "$count" -ne 0 ]]
then
    output="$output "
fi

echo "$output"
echo
echo "$COLOR"
